#!/bin/bash

# Rofi aç ve kullanıcıdan giriş al
input=$(rofi -dmenu -p "Search in Tureng")

# Python sanal ortamını etkinleştir
source /home/aziz/Masaüstü/tureng-rofi/myenv/bin/activate

# Eğer input boş değilse işlemi başlat
if [ -n "$input" ]; then
    # HTML encode işlemi
    encoded_input=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$input'''))")

    # Tureng URL'yi oluştur
    url="https://tureng.com/tr/turkce-ingilizce/$encoded_input"

    # Çıktıyı göster
    echo "Navigating to: $url"
    
    # Python scripti çalıştır, URL'yi işlemek için
    python3 /home/aziz/Masaüstü/tureng-rofi/index.py "$url"
fi

bash /home/aziz/Masaüstü/tureng-rofi/clean_table.sh

cat /home/aziz/Masaüstü/tureng-rofi/clean_rofi_output.txt | rofi -dmenu